POST http://localhost:8080/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI1NjQ5NTg4LCJ1c2VySWQiOjJ9._FcV0156tSm9fcvl4L1zz9YHgEH4P3nKt-M7E2EM3gY

{
    "name": "test event 9",
    "description": "event that should have an actual event id",
    "location": "My house",
    "date_time": "2006-01-02T15:04:05Z"
}

###

GET http://localhost:8080/events

###

GET http://localhost:8080/events/1

###

PUT http://localhost:8080/events/2

{
    "Name": "Second test event",
    "Description": "testing event description",
    "Location": "My house",
    "DateTime": "2006-01-02T15:04:05Z"
}

###

DELETE http://localhost:8080/events/2