POST http://localhost:8080/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjU2Njg3MTUsInVzZXJJZCI6MX0.6Ku4rLvPisF9y9BcvW-lcr1KXZL9IPxFH_rstTFPKVs

{
    "name": "test event",
    "description": "event that should have an actual event id",
    "location": "My house",
    "date_time": "2006-01-02T15:04:05Z"
}

###

GET http://localhost:8080/events

###

GET http://localhost:8080/events/1

###

PUT http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI1NjcwMzIwLCJ1c2VySWQiOjJ9.oJ4P-JVvBxS3I_TPRCgtMc4BwHs2KD1HI-b8Urv66vQ

{
    "name": "Second test event",
    "description": "testing event description",
    "location": "My house",
    "date_time": "2006-01-02T15:04:05Z"
}

###

DELETE http://localhost:8080/events/2

###

POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI1NjcyNDA3LCJ1c2VySWQiOjJ9.lpMB1yzUjbotEmF-wneNVL_EVYxJtjPhmMPBa5XGCVI
